package com.jindb.dao;

import com.jindb.model.BasDutyInfo;
import java.util.List;

public interface BasDutyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_duty_info
     *
     * @mbggenerated
     */
    int insert(BasDutyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_duty_info
     *
     * @mbggenerated
     */
    List<BasDutyInfo> selectAll();
}