package com.jindb.dao;

import com.jindb.model.PubUserInfo;
import java.util.List;

public interface PubUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_user_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_user_info
     *
     * @mbggenerated
     */
    int insert(PubUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_user_info
     *
     * @mbggenerated
     */
    PubUserInfo selectByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_user_info
     *
     * @mbggenerated
     */
    List<PubUserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubUserInfo record);
}