package com.jindb.model;

import java.util.Date;

public class BasDutyInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_duty_info.duty_id
     *
     * @mbggenerated
     */
    private Integer duty_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_duty_info.user_id
     *
     * @mbggenerated
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_duty_info.duty_date
     *
     * @mbggenerated
     */
    private Date duty_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_duty_info.duty_type
     *
     * @mbggenerated
     */
    private String duty_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_duty_info.duty_type_small
     *
     * @mbggenerated
     */
    private String duty_type_small;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_duty_info
     *
     * @mbggenerated
     */
    public BasDutyInfo(Integer duty_id, Integer user_id, Date duty_date, String duty_type, String duty_type_small) {
        this.duty_id = duty_id;
        this.user_id = user_id;
        this.duty_date = duty_date;
        this.duty_type = duty_type;
        this.duty_type_small = duty_type_small;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_duty_info.duty_id
     *
     * @return the value of bas_duty_info.duty_id
     *
     * @mbggenerated
     */
    public Integer getDuty_id() {
        return duty_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_duty_info.user_id
     *
     * @return the value of bas_duty_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_duty_info.duty_date
     *
     * @return the value of bas_duty_info.duty_date
     *
     * @mbggenerated
     */
    public Date getDuty_date() {
        return duty_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_duty_info.duty_type
     *
     * @return the value of bas_duty_info.duty_type
     *
     * @mbggenerated
     */
    public String getDuty_type() {
        return duty_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_duty_info.duty_type_small
     *
     * @return the value of bas_duty_info.duty_type_small
     *
     * @mbggenerated
     */
    public String getDuty_type_small() {
        return duty_type_small;
    }
}