package com.jindb.model;

public class Dic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.code
     *
     * @mbggenerated Tue May 23 17:07:26 CST 2017
     */
    private Integer code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.name
     *
     * @mbggenerated Tue May 23 17:07:26 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.id
     *
     * @mbggenerated Tue May 23 17:07:26 CST 2017
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.code
     *
     * @return the value of dic.code
     *
     * @mbggenerated Tue May 23 17:07:26 CST 2017
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.code
     *
     * @param code the value for dic.code
     *
     * @mbggenerated Tue May 23 17:07:26 CST 2017
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.name
     *
     * @return the value of dic.name
     *
     * @mbggenerated Tue May 23 17:07:26 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.name
     *
     * @param name the value for dic.name
     *
     * @mbggenerated Tue May 23 17:07:26 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.id
     *
     * @return the value of dic.id
     *
     * @mbggenerated Tue May 23 17:07:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.id
     *
     * @param id the value for dic.id
     *
     * @mbggenerated Tue May 23 17:07:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }
}