package com.jindb.model;

import java.util.Date;

public class PubUserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.user_id
     *
     * @mbggenerated
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.dept_id
     *
     * @mbggenerated
     */
    private Integer dept_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.user_name
     *
     * @mbggenerated
     */
    private String user_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.user_no
     *
     * @mbggenerated
     */
    private String user_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.gender_code
     *
     * @mbggenerated
     */
    private String gender_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.post_code
     *
     * @mbggenerated
     */
    private String post_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.degree_code
     *
     * @mbggenerated
     */
    private String degree_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.office_tel
     *
     * @mbggenerated
     */
    private String office_tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.display_no
     *
     * @mbggenerated
     */
    private Short display_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.login_code
     *
     * @mbggenerated
     */
    private String login_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.passwd
     *
     * @mbggenerated
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.create_time
     *
     * @mbggenerated
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.login_time
     *
     * @mbggenerated
     */
    private Date login_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.status_code
     *
     * @mbggenerated
     */
    private String status_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.file_id
     *
     * @mbggenerated
     */
    private Short file_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.photo_url
     *
     * @mbggenerated
     */
    private String photo_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_user_info.user_type
     *
     * @mbggenerated
     */
    private String user_type;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_user_info
     *
     * @mbggenerated
     */
    public PubUserInfo(Integer user_id, Integer dept_id, String user_name, String user_no, String gender_code, String post_code, String degree_code, String mobile, String office_tel, Short display_no, String description, String login_code, String passwd, Date create_time, Date login_time, String status_code, String email, Short file_id, String photo_url, String user_type) {
        this.user_id = user_id;
        this.dept_id = dept_id;
        this.user_name = user_name;
        this.user_no = user_no;
        this.gender_code = gender_code;
        this.post_code = post_code;
        this.degree_code = degree_code;
        this.mobile = mobile;
        this.office_tel = office_tel;
        this.display_no = display_no;
        this.description = description;
        this.login_code = login_code;
        this.passwd = passwd;
        this.create_time = create_time;
        this.login_time = login_time;
        this.status_code = status_code;
        this.email = email;
        this.file_id = file_id;
        this.photo_url = photo_url;
        this.user_type = user_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.user_id
     *
     * @return the value of pub_user_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.dept_id
     *
     * @return the value of pub_user_info.dept_id
     *
     * @mbggenerated
     */
    public Integer getDept_id() {
        return dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.user_name
     *
     * @return the value of pub_user_info.user_name
     *
     * @mbggenerated
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.user_no
     *
     * @return the value of pub_user_info.user_no
     *
     * @mbggenerated
     */
    public String getUser_no() {
        return user_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.gender_code
     *
     * @return the value of pub_user_info.gender_code
     *
     * @mbggenerated
     */
    public String getGender_code() {
        return gender_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.post_code
     *
     * @return the value of pub_user_info.post_code
     *
     * @mbggenerated
     */
    public String getPost_code() {
        return post_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.degree_code
     *
     * @return the value of pub_user_info.degree_code
     *
     * @mbggenerated
     */
    public String getDegree_code() {
        return degree_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.mobile
     *
     * @return the value of pub_user_info.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.office_tel
     *
     * @return the value of pub_user_info.office_tel
     *
     * @mbggenerated
     */
    public String getOffice_tel() {
        return office_tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.display_no
     *
     * @return the value of pub_user_info.display_no
     *
     * @mbggenerated
     */
    public Short getDisplay_no() {
        return display_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.description
     *
     * @return the value of pub_user_info.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.login_code
     *
     * @return the value of pub_user_info.login_code
     *
     * @mbggenerated
     */
    public String getLogin_code() {
        return login_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.passwd
     *
     * @return the value of pub_user_info.passwd
     *
     * @mbggenerated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.create_time
     *
     * @return the value of pub_user_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.login_time
     *
     * @return the value of pub_user_info.login_time
     *
     * @mbggenerated
     */
    public Date getLogin_time() {
        return login_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.status_code
     *
     * @return the value of pub_user_info.status_code
     *
     * @mbggenerated
     */
    public String getStatus_code() {
        return status_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.email
     *
     * @return the value of pub_user_info.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.file_id
     *
     * @return the value of pub_user_info.file_id
     *
     * @mbggenerated
     */
    public Short getFile_id() {
        return file_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.photo_url
     *
     * @return the value of pub_user_info.photo_url
     *
     * @mbggenerated
     */
    public String getPhoto_url() {
        return photo_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_user_info.user_type
     *
     * @return the value of pub_user_info.user_type
     *
     * @mbggenerated
     */
    public String getUser_type() {
        return user_type;
    }
}